import { describe, it, expect, afterEach } from "vitest";
import { unlinkSync, existsSync } from "node:fs";
import { openCodeIntelligenceDb } from "../agent/lib/code-intelligence-db";

const TEST_DB_PATH = "/tmp/code-intelligence-schema-test.sqlite";

describe("openCodeIntelligenceDb", () => {
  afterEach(() => {
    if (existsSync(TEST_DB_PATH)) unlinkSync(TEST_DB_PATH);
  });

  it("creates symbols, edges, chunks, and chunks_vec tables", () => {
    const db = openCodeIntelligenceDb(TEST_DB_PATH);
    const tableNames = db
      .prepare("SELECT name FROM sqlite_master WHERE type IN ('table', 'virtual table')")
      .all()
      .map((row: any) => row.name)
      .sort();
    expect(tableNames).toEqual(
      expect.arrayContaining(["symbols", "edges", "chunks", "chunks_vec"]),
    );
    db.close();
  });

  it("can insert and read back a symbol row", () => {
    const db = openCodeIntelligenceDb(TEST_DB_PATH);
    db.prepare(
      "INSERT INTO symbols (id, name, kind, file, start_line, end_line, language) VALUES (?, ?, ?, ?, ?, ?, ?)",
    ).run("pkg/models/x.go:CanDelete:10", "CanDelete", "method", "pkg/models/x.go", 10, 20, "go");
    const row = db.prepare("SELECT * FROM symbols WHERE id = ?").get("pkg/models/x.go:CanDelete:10") as any;
    expect(row.name).toBe("CanDelete");
    db.close();
  });

  it("readonly mode works when file exists and throws when file does not exist", () => {
    // First, create and populate a database
    const dbWrite = openCodeIntelligenceDb(TEST_DB_PATH);
    dbWrite.prepare(
      "INSERT INTO symbols (id, name, kind, file, start_line, end_line, language) VALUES (?, ?, ?, ?, ?, ?, ?)",
    ).run("pkg/models/x.go:TestFunc:5", "TestFunc", "function", "pkg/models/x.go", 5, 15, "go");
    dbWrite.close();

    // Open the same file in readonly mode — should work without throwing
    const dbReadonly = openCodeIntelligenceDb(TEST_DB_PATH, { readonly: true });
    const row = dbReadonly.prepare("SELECT * FROM symbols WHERE id = ?").get("pkg/models/x.go:TestFunc:5") as any;
    expect(row.name).toBe("TestFunc");
    dbReadonly.close();

    // Try opening a non-existent file in readonly mode — should throw
    const nonExistentPath = "/tmp/non-existent-code-intelligence-db.sqlite";
    if (existsSync(nonExistentPath)) unlinkSync(nonExistentPath);
    expect(() => {
      openCodeIntelligenceDb(nonExistentPath, { readonly: true });
    }).toThrow();
  });

  it("sqlite-vec extension loads and works for vector queries", () => {
    const db = openCodeIntelligenceDb(TEST_DB_PATH);

    // Insert a fixed-length vector (1024-dimensional, all values 0.1)
    const embedding = new Array(1024).fill(0.1);
    const embeddingJson = JSON.stringify(embedding);

    // Use vec_f32() function to properly encode the vector for insertion
    // Let rowid be auto-generated by inserting without specifying it
    const insertResult = db.prepare("INSERT INTO chunks_vec (embedding) VALUES (vec_f32(?))").run(embeddingJson);

    // Query using vector search with MATCH and distance
    const queryEmbedding = new Array(1024).fill(0.1);
    const queryJson = JSON.stringify(queryEmbedding);

    const result = db.prepare(
      "SELECT rowid FROM chunks_vec WHERE embedding MATCH vec_f32(?) ORDER BY distance LIMIT 1"
    ).get(queryJson) as any;

    // Confirm we got a result and it has a valid rowid
    expect(result?.rowid).toBeDefined();
    expect(typeof result?.rowid).toBe("number");
    db.close();
  });
});
